### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by bjornsivertsen** [madmic1314/ha_strava#8]
Hi, HA throws this error, and although the integration works perfectly, I just wanted to log it.
It only happens at initialization of the component.

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/ha_strava/__init__.py:417
Integration: HA Strava (documentation)
First occurred: 09:45:57 (2 occurrences)
Last logged: 09:46:24

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
    await waiter
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ha_strava/__init__.py", line 560, in strava_startup_functions
    await renew_webhook_subscription(
  File "/config/custom_components/ha_strava/__init__.py", line 417, in renew_webhook_subscription
    callback_response = await websession.get(url=config_data[CONF_CALLBACK_URL])
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host un4ne7yr6ue8u402igjf1f18fy62ybnh.ui.nabu.casa:443 ssl:default [None]
```

**Comment by madmic1314** [comment]
Seems the error was it couldn't connect to your nabucasa host:
"aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host un4ne7yr6ue8u402igjf1f18fy62ybnh.ui.nabu.casa:443 ssl:default [None]"

I'll do some more testing and see, but if you see this happen again be good to know.

I'm currently setting up a dev env on a Pi4 - a bit of a learning curve to say the least so please bare with!

**Comment by bjornsivertsen** [comment]
Agreed, it seems to only appear on device startup. So I will just ignore it going forward.
