### ISSUE TITLE
Camera Image Broken

### ISSUE THREAD

**Issue by moseisleydk** [madmic1314/ha_strava#9]
In Newest HA:

`2022-04-17T09:17:46.264257842Z 2022-04-17 11:17:46 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: dict object has no element 1 when rendering '{{ value_json.1.value }}'
2022-04-17T09:17:46.276136155Z 2022-04-17 11:17:46 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: dict object has no element 0 when rendering '{{ value_json.0.value }}'
2022-04-17T09:17:54.841698217Z 2022-04-17 11:17:54 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
2022-04-17T09:17:54.841732977Z Traceback (most recent call last):
2022-04-17T09:17:54.841738405Z   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
2022-04-17T09:17:54.841742473Z     result = self.fn(*self.args, **self.kwargs)
2022-04-17T09:17:54.841745810Z   File "/config/custom_components/ha_strava/camera.py", line 168, in img_update_handler
2022-04-17T09:17:54.841749391Z     self._urls = {
2022-04-17T09:17:54.841752724Z TypeError: unhashable type: 'slice'
2022-04-17T09:17:55.001532169Z 2022-04-17 11:17:55 ERROR (MainThread) [homeassistant.components.google_assistant.http] No configuration for request_sync available`

**Comment by moseisleydk** [comment]
Pretty sure I saw something regarding this previously either here or at [ the ](https://github.com/codingcyclist/ha_strava) - But I can find it anymore...

**Comment by moseisleydk** [comment]
I the log file, the URLS seems valid:

[strava_cam](https://homeassistant.mos-eisley.dk/logbook#) changed to https://dgtzuqphqg23d.cloudfront.net/lRwE0t7fVAGRcQwOOcRhI9tdLFPRtaJTl3M20ysouH0-512x384.jpg
5:24:00 PM - 1 minute ago
[strava_cam](https://homeassistant.mos-eisley.dk/logbook#) changed to https://dgtzuqphqg23d.cloudfront.net/wcKfC4OqGw-RwwdNFZmyMdkMBNAybDxy6luA5Q-gmCc-512x384.jpg
5:23:45 PM - 1 minute ago

But the image is broken in lovelace:

type: picture-glance
aspect_ratio: 0%
camera_image: camera.strava_cam
entities: []
